backend:
  image: imswede/devops-backend:${IMAGE_TAG}
  container_name: backend
  ports:
    - "8000:8000"
  environment:
    DB_HOST: db
    DB_PORT: 5432
    DB_NAME: devdb
    DB_USER: devuser
    DB_PASSWORD: devpass
  depends_on:
    - db

frontend:
  image: imswede/devops-frontend:${IMAGE_TAG}
  container_name: frontend
  ports:
    - "3000:80"
  depends_on:
    - backend